/**
 * Journey Model
 * Tracks a user's voting readiness progress through each key stage.
 * Eligibility → Documents → Registration → Voting Ready
 */

const mongoose = require('mongoose');

const journeySchema = new mongoose.Schema(
  {
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      maxlength: 64,
    },

    // Each stage tracks completion and notes
    steps: {
      eligibility: {
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
        notes: { type: String, maxlength: 500 },
      },
      documents: {
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
        notes: { type: String, maxlength: 500 },
      },
      registration: {
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
        notes: { type: String, maxlength: 500 },
      },
      voting: {
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
        notes: { type: String, maxlength: 500 },
      },
    },

    // Current active stage in the journey
    currentStage: {
      type: String,
      enum: ['eligibility', 'documents', 'registration', 'voting', 'complete'],
      default: 'eligibility',
    },

    // Calculated readiness percentage (0–100)
    readinessScore: {
      type: Number,
      min: 0,
      max: 100,
      default: 0,
    },

    // List of warnings generated by the Mistake Prevention engine
    warnings: [
      {
        message: { type: String, required: true, maxlength: 300 },
        stage: { type: String },
        createdAt: { type: Date, default: Date.now },
      },
    ],
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

/**
 * Recalculates readiness score based on completed steps.
 * Each step is worth 25 points (4 steps × 25 = 100).
 */
journeySchema.methods.calculateReadiness = function () {
  const steps = this.steps;
  const completed = [
    steps.eligibility.completed,
    steps.documents.completed,
    steps.registration.completed,
    steps.voting.completed,
  ].filter(Boolean).length;

  this.readinessScore = completed * 25;
  return this.readinessScore;
};

module.exports = mongoose.model('Journey', journeySchema);
